CLEAR SCREEN;

DROP TABLE PLAY_BOARD CASCADE CONSTRAINTS;

CREATE TABLE PLAY_BOARD(
    ROW_LEBEL int,
    POS1 varchar2(10),
    POS2 varchar2(10),
	POS3 varchar2(10));
	
INSERT INTO PLAY_BOARD(ROW_LEBEL, POS1, POS2, POS3) VALUES(1, ' ', ' ', ' ');
INSERT INTO PLAY_BOARD(ROW_LEBEL, POS1, POS2, POS3) VALUES(2, ' ', ' ', ' ');
INSERT INTO PLAY_BOARD(ROW_LEBEL, POS1, POS2, POS3) VALUES(3, ' ', ' ', ' ');

SELECT * FROM PLAY_BOARD;

commit;